//package ceshi;
///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//
//import org.jfree.chart.ChartPanel;
//import org.jfree.chart.ChartFactory;
//import org.jfree.chart.JFreeChart;
//import org.jfree.data.category.DefaultCategoryDataset;
//import org.jfree.chart.plot.PlotOrientation;
//import javax.swing.table.DefaultTableModel;
///**
// *
// * @author 14338
// */
//public class f17 extends javax.swing.JFrame {
//
//    /**
//     * Creates new form f17
//     */
//    public f17() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tablevisitor = new javax.swing.JTable();
//        panelChart = new javax.swing.JPanel();
//        DisplayButton = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setText("图书馆访问者统计器");
//
//        jLabel2.setText("- - - - - - - -  - - - - - - - - - - - - - - - ");
//
//        tablevisitor.setModel(new javax.swing.table.DefaultTableModel(
//                new Object [][] {
//                        {null, null},
//                        {null, null},
//                        {null, null},
//                        {null, null}
//                },
//                new String [] {
//                        "年份", "访问人数"
//                }
//        ));
//        jScrollPane1.setViewportView(tablevisitor);
//
//        javax.swing.GroupLayout panelChartLayout = new javax.swing.GroupLayout(panelChart);
//        panelChart.setLayout(panelChartLayout);
//        panelChartLayout.setHorizontalGroup(
//                panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 559, Short.MAX_VALUE)
//        );
//        panelChartLayout.setVerticalGroup(
//                panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 267, Short.MAX_VALUE)
//        );
//
//        DisplayButton.setText("显示统计数据");
//        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                DisplayButtonActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(110, 110, 110)
//                                                .addComponent(jLabel1))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(jLabel2))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(DisplayButton))
//                                                .addGap(18, 18, 18)
//                                                .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jLabel1)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jLabel2)
//                                .addGap(18, 18, 18)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(DisplayButton))
//                                        .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(17, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {
//        Integer [][]visitordata={{2004,1500},{2005,1450},{2006,2000},{2007,2050},{2008,2500},{2009,2000},{2010,1600},{2011,3000},{2012,3200},{2013,4000},{2014,3500},{2015,2000},{2016,2300}};
//        String []title = {"年份","访问人数"};
//
//        //显示数据到表格中
//        DefaultTableModel model = new DefaultTableModel();
//        model.setDataVector(visitordata, title);
//        tablevisitor.setModel(model);
//
//        //创建访问人数的图表
//        DefaultCategoryDataset chart_dataset = new DefaultCategoryDataset();
//        for(int i=0;i<12;i++)
//        {
//            chart_dataset.addValue(visitordata[i][1], "666666", visitordata[i][0]);
//        }
//
//        JFreeChart lineChart = ChartFactory.createLineChart("图书馆访问人员统计表图","年份","访问人数",chart_dataset,PlotOrientation.VERTICAL, true, true, false);
//        ChartPanel chartpanel = new ChartPanel(lineChart);
//        chartpanel.setSize(panelChart.getSize());
//        panelChart.removeAll();
//        panelChart.add(chartpanel);
//        panelChart.validate();        // TODO add your handling code here:
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(f17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(f17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(f17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(f17.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new f17().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton DisplayButton;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JPanel panelChart;
//    private javax.swing.JTable tablevisitor;
//    // End of variables declaration
//}
